---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: default-easyrsa
    run_list:
      - recipe[openvpn2::default]
    data_bags_path: "test/data_bags"
    attributes:
      openvpn2:
        provisioner: easyrsa
  - name: default-authority
    run_list:
      - recipe[openvpn2::default]
    data_bags_path: "test/data_bags"
    attributes:
      openvpn2:
        provisioner: authority
